### ISSUE TITLE
How to build terminal only without X11 requirements?

### ISSUE THREAD

**Issue by casper** [mittelmark/microemacs#2]
Is it possible to build a terminal only version from source, without needing the X11 development libraries installed?  Thanks.

**Comment by mittelmark** [comment]
Thanks for the comment. I modified the Makefile, separating the terminal from the windows build so that it should be now possible to build a terminal version without the X11 libraries. It should work like this after pulling the new Makefile from the repo (it now only needs the ncurses-library):

cd microemacs ## switching into the repo
git pull
make mec-bin ## builds src/mec
make bfs-bin   ## builds the bfs exe packer
make mec-bfs-linux ## builds some mec-osname.bin which contains all macros, the help file, the American dictionary and the executable

Give it a try. Worked on my Debian 12 machine (MX Linux)

**Comment by mittelmark** [comment]
Try then ./mec-osname.bin -V ## where osname is your operating system

**Comment by casper** [comment]
Awesome. Thanks for the fix. It works! :)

**Comment by mittelmark** [comment]
Nice to hear that. The default Makefile was a little bit overloaded.

I now created three new ones, one for mac, one for building the windows version on Linux and the linux version.
So in the root folder you just might try:

cd microemacs
make -f linux32gcc.gmk mecb

to get the single file mecb executable. The name depends on the platform, distro you are.

Github actions at least does not have a problem with producing the binaries that way.

https://github.com/mittelmark/microemacs/actions/workflows/binaries-linux.yml

**Comment by mittelmark** [comment]
Seems to be fine! Let's close it now.
